#!/usr/bin/env node
'use strict';

/**
 * Synthetic data generator for a flood-monitoring alert system.
 *
 * No external dependencies.
 *
 * Usage:
 *   node generate_monitoring_data_node_v2.js --days 14 --output synthetic_data
 *   node generate_monitoring_data_node_v2.js --days 30 --seed 123 --output synthetic_data --sql
 */

const fs = require('fs');
const path = require('path');

/**
 * Deterministic pseudo-random generator.
 * @param {number} seed
 * @returns {() => number}
 */
function makeRng(seed) {
  let state = seed >>> 0;
  return () => {
    state += 0x6D2B79F5;
    let x = state;
    x = Math.imul(x ^ (x >>> 15), x | 1);
    x ^= x + Math.imul(x ^ (x >>> 7), x | 61);
    return ((x ^ (x >>> 14)) >>> 0) / 4294967296;
  };
}

/** @param {number} x @param {number} a @param {number} b */
const clamp = (x, a, b) => Math.max(a, Math.min(b, x));

/** @param {number} x @param {number} d */
const round = (x, d = 2) => Math.round(x * 10 ** d) / 10 ** d;

/** @param {() => number} rng @param {number} a @param {number} b */
const uniform = (rng, a, b) => a + (b - a) * rng();

/** @param {() => number} rng @param {number} a @param {number} b */
const randint = (rng, a, b) => Math.floor(uniform(rng, a, b + 1));

/**
 * Gaussian random value with Box-Muller transform.
 * @param {() => number} rng
 * @param {number} mean
 * @param {number} sd
 */
function gaussian(rng, mean = 0, sd = 1) {
  const u1 = Math.max(rng(), Number.EPSILON);
  const u2 = Math.max(rng(), Number.EPSILON);
  return mean + sd * Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
}

/**
 * Weighted choice.
 * @template T
 * @param {() => number} rng
 * @param {Array<[T, number]>} options
 * @returns {T}
 */
function weightedChoice(rng, options) {
  const total = options.reduce((acc, [, w]) => acc + w, 0);
  let cursor = rng() * total;

  for (const [value, weight] of options) {
    cursor -= weight;
    if (cursor <= 0) return value;
  }

  return options[options.length - 1][0];
}

/**
 * MySQL-compatible UTC datetime.
 * @param {Date} date
 * @returns {string}
 */
function mysqlDate(date) {
  const p = (x) => String(x).padStart(2, '0');
  return `${date.getUTCFullYear()}-${p(date.getUTCMonth() + 1)}-${p(date.getUTCDate())} ${p(date.getUTCHours())}:${p(date.getUTCMinutes())}:${p(date.getUTCSeconds())}`;
}

/** @param {Date} d @param {number} h */
const addHours = (d, h) => new Date(d.getTime() + h * 3600_000);

/** @param {Date} d @param {number} m */
const addMinutes = (d, m) => new Date(d.getTime() + m * 60_000);

/**
 * Escape CSV value.
 * @param {unknown} value
 * @returns {string}
 */
function csvValue(value) {
  if (value === null || value === undefined) return '';
  const text = String(value);
  return /[",\n\r]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

/**
 * Write rows to CSV.
 * @param {string} filePath
 * @param {Array<Record<string, unknown>>} rows
 */
function writeCsv(filePath, rows) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });

  if (rows.length === 0) {
    fs.writeFileSync(filePath, '', 'utf8');
    return;
  }

  const columns = Object.keys(rows[0]);
  const lines = [
    columns.join(','),
    ...rows.map((row) => columns.map((col) => csvValue(row[col])).join(',')),
  ];

  fs.writeFileSync(filePath, `${lines.join('\n')}\n`, 'utf8');
}

/**
 * Convert a value to a SQL literal.
 * @param {unknown} value
 * @returns {string}
 */
function sqlLiteral(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "''")}'`;
}

/**
 * Write MySQL INSERT script.
 * @param {string} filePath
 * @param {Record<string, Array<Record<string, unknown>>>} tables
 */
function writeSql(filePath, tables) {
  const lines = [
    '-- Synthetic data generated by generate_monitoring_data_node_v2.js',
    'SET FOREIGN_KEY_CHECKS = 0;',
    '',
  ];

  for (const [tableName, rows] of Object.entries(tables)) {
    if (rows.length === 0) continue;

    const columns = Object.keys(rows[0]);
    const columnSql = columns.map((c) => `\`${c}\``).join(', ');

    lines.push(`-- Table: ${tableName}`);

    for (const row of rows) {
      const values = columns.map((c) => sqlLiteral(row[c])).join(', ');
      lines.push(`INSERT INTO \`${tableName}\` (${columnSql}) VALUES (${values});`);
    }

    lines.push('');
  }

  lines.push('SET FOREIGN_KEY_CHECKS = 1;', '');
  fs.writeFileSync(filePath, lines.join('\n'), 'utf8');
}

/** @returns {Array<Record<string, unknown>>} */
function buildAreas() {
  return [
    {
      idarea_risco: 1,
      nome: 'Zona Ribeirinha',
      localizacao: 'Vila do Conde - Marginal e Rio Ave',
      vulnerabilidade_base: 5,
      descricao: 'Área baixa próxima do rio, sensível a maré cheia e precipitação acumulada.',
    },
    {
      idarea_risco: 2,
      nome: 'Passagem Inferior',
      localizacao: 'Vila do Conde - Acesso rodoviário inferior',
      vulnerabilidade_base: 4,
      descricao: 'Zona com histórico de acumulação rápida de água em eventos intensos.',
    },
    {
      idarea_risco: 3,
      nome: 'Centro Urbano',
      localizacao: 'Vila do Conde - Centro',
      vulnerabilidade_base: 3,
      descricao: 'Zona urbana impermeabilizada, com risco de lençóis de água.',
    },
    {
      idarea_risco: 4,
      nome: 'Zona Industrial',
      localizacao: 'Vila do Conde - Área industrial',
      vulnerabilidade_base: 2,
      descricao: 'Zona com risco moderado e dependente da capacidade de drenagem.',
    },
  ];
}

/**
 * @param {Array<Record<string, unknown>>} areas
 * @returns {Array<Record<string, unknown>>}
 */
function buildInfra(areas) {
  const rows = [];
  let id = 1;

  for (const area of areas) {
    for (const [label, tipo] of [
      ['Coletor Principal', 'coletor_pluvial'],
      ['Sarjeta Crítica', 'sarjeta'],
      ['Ponto de Drenagem', 'drenagem'],
    ]) {
      rows.push({
        idinfraestrutura_urbana: id++,
        nome: `${label} - ${area.nome}`,
        tipo,
        localizacao: area.localizacao,
        idarea_risco: area.idarea_risco,
      });
    }
  }

  return rows;
}

/**
 * @param {Array<Record<string, unknown>>} infra
 * @param {() => number} rng
 * @param {Date} start
 * @returns {Array<Record<string, unknown>>}
 */
function buildSensors(infra, rng, start) {
  const rows = [];
  let id = 1;

  for (const item of infra) {
    for (const tipo of ['nivel_agua', 'precipitacao', 'caudal']) {
      rows.push({
        idsensor: id++,
        tipo,
        localizacao: item.localizacao,
        status: rng() > 0.04 ? 1 : 0,
        idinfraestrutura_urbana: item.idinfraestrutura_urbana,
        data_proxima_manutencao: mysqlDate(addHours(start, 24 * randint(rng, 15, 120))),
      });
    }
  }

  return rows;
}

/** @returns {Array<Record<string, unknown>>} */
function buildNiveis() {
  return [
    [1, 'Verde', 1, 'Monitorização preventiva.'],
    [2, 'Amarelo', 2, 'Vigilância ativa.'],
    [3, 'Laranja', 3, 'Proteção e mobilização.'],
    [4, 'Vermelho', 4, 'Emergência e salvaguarda.'],
  ].map(([idnivel_alerta, nome, ordem_gravidade, descricao]) => ({
    idnivel_alerta,
    nome,
    cor: nome,
    ordem_gravidade,
    descricao,
  }));
}

/** @returns {Array<Record<string, unknown>>} */
function buildCriterios() {
  const rows = [
    [1, 1, 'precipitacao_prevista_1h', '<', null, 10, 60, 'Ativação verde: precipitação prevista inferior a 10 mm na próxima hora.'],
    [2, 2, 'precipitacao_prevista_1h', 'between', 10, 20, 60, 'Ativação amarela: precipitação prevista entre 10 e 20 mm na próxima hora.'],
    [3, 3, 'precipitacao_prevista_1h', 'between', 21, 40, 60, 'Ativação laranja: precipitação prevista entre 21 e 40 mm na próxima hora.'],
    [4, 4, 'precipitacao_prevista_1h', '>', 40, null, 60, 'Ativação vermelha: precipitação prevista superior a 40 mm na próxima hora.'],
    [5, 2, 'nivel_agua_percentagem', 'between', 70, 85, 0, 'Nível de água entre 70% e 85%.'],
    [6, 3, 'nivel_agua_percentagem', 'between', 85, 90, 0, 'Nível de água entre 85% e 90%.'],
    [7, 4, 'nivel_agua_percentagem', '>=', 90, null, 0, 'Nível de água igual ou superior a 90%.'],
    [8, 4, 'precipitacao_acumulada_6h', '>', 60, null, 360, 'Precipitação acumulada superior a 60 mm nas últimas 6 horas.'],
  ];

  return rows.map(([idcriterio, idnivel_alerta, variavel, operador, limiar_min, limiar_max, janela_temporal_minutos, descricao]) => ({
    idcriterio,
    idnivel_alerta,
    variavel,
    operador,
    limiar_min,
    limiar_max,
    janela_temporal_minutos,
    descricao,
    ativo: 1,
  }));
}

/** @returns {Array<Record<string, unknown>>} */
function buildUsers() {
  return [
    {
      idutilizador: 1,
      tipo: 'administrador',
      email: 'admin.monitorizacao@example.pt',
      password_hash: 'hash_demo_admin_please_replace',
    },
    {
      idutilizador: 2,
      tipo: 'operador_municipal',
      email: 'operador.municipal@example.pt',
      password_hash: 'hash_demo_operator_please_replace',
    },
    {
      idutilizador: 3,
      tipo: 'analista_risco',
      email: 'analista.risco@example.pt',
      password_hash: 'hash_demo_analyst_please_replace',
    },
  ];
}

/** @returns {Array<Record<string, unknown>>} */
function buildDestinatarios() {
  return [
    ['administrador', 'Administrador do Sistema'],
    ['operador_municipal', 'Operador Municipal'],
    ['protecao_civil', 'Proteção Civil Municipal'],
    ['bombeiros', 'Bombeiros Voluntários'],
    ['policia_municipal', 'Polícia Municipal'],
    ['gestao_infraestrutura', 'Gestão de Infraestrutura'],
    ['populacao_civil', 'População Civil - Zona de Risco'],
    ['hospital', 'Unidade Hospitalar Local'],
  ].map(([tipo, nome], i) => ({
    iddestinatario: i + 1,
    tipo,
    nome,
    email: `${tipo.replaceAll('_', '.')}@example.pt`,
    contato: `+35191000000${i + 1}`,
  }));
}

/** @returns {{plano_acao: Array<Record<string, unknown>>, plano_alerta: Array<Record<string, unknown>>}} */
function buildPlanos() {
  const plano_acao = [
    [1, 'Verificar obstrução de sarjetas e coletores em zonas baixas.', 'gestao_infraestrutura'],
    [2, 'Analisar modelos preditivos para as próximas 24 horas.', 'operador_municipal'],
    [3, 'Colocar equipas de piquete em prontidão.', 'gestao_infraestrutura'],
    [4, 'Verificar equipamentos de bombagem e drenagem.', 'bombeiros'],
    [5, 'Preparar corte preventivo de vias com risco de inundação.', 'policia_municipal'],
    [6, 'Pré-posicionar meios de socorro em locais estratégicos.', 'protecao_civil'],
    [7, 'Ativar plano municipal de emergência.', 'protecao_civil'],
    [8, 'Executar evacuação e apoio à população nas zonas críticas.', 'populacao_civil'],
  ].map(([idplano_acao, descricao, tipo_destinatario]) => ({
    idplano_acao,
    descricao,
    tipo_destinatario,
  }));

  const plano_alerta = [
    [1, 1],
    [2, 1],
    [1, 2],
    [3, 2],
    [4, 2],
    [3, 3],
    [5, 3],
    [6, 3],
    [5, 4],
    [6, 4],
    [7, 4],
    [8, 4],
  ].map(([idplano_acao, idnivel_alerta]) => ({ idplano_acao, idnivel_alerta }));

  return { plano_acao, plano_alerta };
}

/**
 * @param {number} water
 * @param {number} rain6h
 * @param {number} forecast1h
 * @returns {{idnivel_alerta: number, cor: string, score_risco: number, razoes: string[]}}
 */
function classifyAlert(water, rain6h, forecast1h) {
  const razoes = [];
  let waterScore = 1;
  let rainScore = 1;
  let forecastScore = 1;

  if (water >= 90) {
    waterScore = 4;
    razoes.push('Nível de água superior ou igual a 90%.');
  } else if (water >= 85) {
    waterScore = 3;
    razoes.push('Nível de água entre 85% e 90%.');
  } else if (water >= 70) {
    waterScore = 2;
    razoes.push('Nível de água entre 70% e 85%.');
  }

  if (rain6h > 60) {
    rainScore = 4;
    razoes.push('Precipitação acumulada superior a 60 mm nas últimas 6 horas.');
  } else if (rain6h >= 41) {
    rainScore = 3;
    razoes.push('Precipitação acumulada entre 41 e 60 mm nas últimas 6 horas.');
  } else if (rain6h >= 30) {
    rainScore = 2;
    razoes.push('Precipitação acumulada entre 30 e 40 mm nas últimas 6 horas.');
  }

  if (forecast1h > 40) {
    forecastScore = 4;
    razoes.push('Precipitação prevista superior a 40 mm na próxima hora.');
  } else if (forecast1h >= 21) {
    forecastScore = 3;
    razoes.push('Precipitação prevista entre 21 e 40 mm na próxima hora.');
  } else if (forecast1h >= 10) {
    forecastScore = 2;
    razoes.push('Precipitação prevista entre 10 e 20 mm na próxima hora.');
  }

  const scores = [waterScore, rainScore, forecastScore];
  const critical = scores.some((s) => s >= 4);
  const high = scores.some((s) => s >= 3);
  const moderateCount = scores.filter((s) => s >= 2).length;

  const score_risco = round(clamp(
    0.45 * water + 0.30 * Math.min(rain6h, 80) + 0.25 * Math.min(forecast1h, 60),
    0,
    100,
  ), 2);

  if (critical) return { idnivel_alerta: 4, cor: 'Vermelho', score_risco, razoes };
  if (high || moderateCount >= 2) return { idnivel_alerta: 3, cor: 'Laranja', score_risco, razoes };
  if (moderateCount >= 1) return { idnivel_alerta: 2, cor: 'Amarelo', score_risco, razoes };

  return {
    idnivel_alerta: 1,
    cor: 'Verde',
    score_risco,
    razoes: ['Valores abaixo dos limites iniciais.'],
  };
}

/**
 * @param {number} h
 * @param {number} totalHours
 * @param {() => number} rng
 * @returns {number}
 */
function rainfallPattern(h, totalHours, rng) {
  const seasonal = 2 + 2 * Math.sin((2 * Math.PI * h) / Math.max(totalHours, 1));
  const baseline = Math.max(0, gaussian(rng, seasonal, 1.5));

  if (rng() < 0.07) return round(baseline + uniform(rng, 8, 35), 2);
  if (rng() < 0.02) return round(baseline + uniform(rng, 35, 60), 2);

  return round(baseline, 2);
}

/**
 * @param {number} vulnerability
 * @param {number} rain6h
 * @param {number} previous
 * @param {() => number} rng
 * @returns {number}
 */
function waterLevelFromRain(vulnerability, rain6h, previous, rng) {
  return round(clamp(
    15 + vulnerability * 3 + rain6h * 0.75 + previous * 0.55 * 0.25 + gaussian(rng, 0, 3.5),
    5,
    100,
  ), 2);
}

/**
 * @param {number} level
 * @param {Array<Record<string, unknown>>} destinatarios
 * @returns {Array<Record<string, unknown>>}
 */
function recipientsForLevel(level, destinatarios) {
  const byType = Object.fromEntries(destinatarios.map((d) => [d.tipo, d]));
  const map = {
    1: ['administrador', 'operador_municipal'],
    2: ['administrador', 'operador_municipal', 'protecao_civil', 'bombeiros', 'gestao_infraestrutura'],
    3: ['administrador', 'operador_municipal', 'protecao_civil', 'bombeiros', 'policia_municipal', 'gestao_infraestrutura', 'populacao_civil'],
    4: ['administrador', 'operador_municipal', 'protecao_civil', 'bombeiros', 'policia_municipal', 'gestao_infraestrutura', 'populacao_civil', 'hospital'],
  };

  return map[level].map((t) => byType[t]).filter(Boolean);
}

/**
 * Generate all synthetic tables.
 * @param {{days: number, seed: number, start: Date}} cfg
 * @returns {Record<string, Array<Record<string, unknown>>>}
 */
function generateData(cfg) {
  if (!Number.isInteger(cfg.days) || cfg.days <= 0) {
    throw new Error('days must be a positive integer.');
  }

  const rng = makeRng(cfg.seed);
  const totalHours = cfg.days * 24;

  const area_risco = buildAreas();
  const infraestrutura_urbana = buildInfra(area_risco);
  const sensor = buildSensors(infraestrutura_urbana, rng, cfg.start);
  const nivel_alerta = buildNiveis();
  const criterio_alerta = buildCriterios();
  const utilizador = buildUsers();
  const destinatario = buildDestinatarios();
  const { plano_acao, plano_alerta } = buildPlanos();

  const areaById = Object.fromEntries(area_risco.map((a) => [a.idarea_risco, a]));
  const sensorsByInfra = {};
  for (const s of sensor) {
    sensorsByInfra[s.idinfraestrutura_urbana] ??= [];
    sensorsByInfra[s.idinfraestrutura_urbana].push(s);
  }

  const leitura_sensor = [];
  const previsao_meteorologica = [];
  const alerta = [];
  const alerta_evidencia = [];
  const alerta_destinatario = [];
  const notificacao = [];
  const alerta_plano_acao = [];
  const relatorio = [];

  let idleitura_sensor = 1;
  let idprevisao = 1;
  let idalerta = 1;
  let idalerta_evidencia = 1;
  let idnotificacao = 1;
  let idrelatorio = 1;

  const previousWater = Object.fromEntries(
    infraestrutura_urbana.map((i) => [i.idinfraestrutura_urbana, uniform(rng, 15, 35)]),
  );
  const rainHistory = Object.fromEntries(area_risco.map((a) => [a.idarea_risco, []]));

  for (let h = 0; h < totalHours; h += 1) {
    const observed = addHours(cfg.start, h);
    const observedText = mysqlDate(observed);
    const currentWaterByArea = Object.fromEntries(area_risco.map((a) => [a.idarea_risco, []]));
    const rainThisHour = {};

    for (const area of area_risco) {
      const rawRain = rainfallPattern(h, totalHours, rng);
      const rain = round(rawRain * (1 + (area.vulnerabilidade_base - 3) * 0.07), 2);
      rainThisHour[area.idarea_risco] = Math.max(0, rain);

      rainHistory[area.idarea_risco].push(rain);
      while (rainHistory[area.idarea_risco].length > 6) rainHistory[area.idarea_risco].shift();

      const forecast = round(clamp(rain + gaussian(rng, 0, 8) + uniform(rng, -3, 12), 0, 70), 2);

      previsao_meteorologica.push({
        idprevisao,
        idarea_risco: area.idarea_risco,
        fonte: 'IPMA_simulado',
        data_emissao: observedText,
        data_inicio_previsao: observedText,
        data_fim_previsao: mysqlDate(addHours(observed, 1)),
        horizonte_horas: 1,
        precipitacao_prevista_mm: forecast,
        confianca: round(uniform(rng, 0.65, 0.95), 3),
      });
      idprevisao += 1;
    }

    for (const infra of infraestrutura_urbana) {
      const area = areaById[infra.idarea_risco];
      const rain6h = round(rainHistory[area.idarea_risco].reduce((acc, x) => acc + x, 0), 2);
      const water = waterLevelFromRain(area.vulnerabilidade_base, rain6h, previousWater[infra.idinfraestrutura_urbana], rng);
      previousWater[infra.idinfraestrutura_urbana] = water;

      const flow = round(clamp(water * uniform(rng, 0.6, 1.35), 0, 130), 2);

      for (const s of sensorsByInfra[infra.idinfraestrutura_urbana]) {
        if (s.status === 0 && rng() > 0.25) continue;

        const qualidade_dado = s.status === 0 ? 'falha' : (rng() > 0.08 ? 'boa' : 'suspeita');
        const validada = qualidade_dado === 'boa' ? 1 : 0;

        let tipo_variavel;
        let valor;
        let unidade;

        if (s.tipo === 'nivel_agua') {
          tipo_variavel = 'nivel_agua_percentagem';
          valor = water;
          unidade = '%';
        } else if (s.tipo === 'precipitacao') {
          tipo_variavel = 'precipitacao_horaria';
          valor = rainThisHour[area.idarea_risco];
          unidade = 'mm';
        } else {
          tipo_variavel = 'caudal_estimado';
          valor = flow;
          unidade = 'm3/s';
        }

        const row = {
          idleitura_sensor,
          idsensor: s.idsensor,
          tipo_variavel,
          valor,
          unidade,
          data_observacao: observedText,
          data_registo: mysqlDate(addMinutes(observed, randint(rng, 0, 5))),
          qualidade_dado,
          validada,
        };

        leitura_sensor.push(row);

        if (tipo_variavel === 'nivel_agua_percentagem' && validada === 1) {
          currentWaterByArea[area.idarea_risco].push(row);
        }

        idleitura_sensor += 1;
      }
    }

    for (const area of area_risco) {
      const waterRows = currentWaterByArea[area.idarea_risco];
      if (!waterRows.length) continue;

      const maxWaterRow = waterRows.reduce((best, row) => row.valor > best.valor ? row : best, waterRows[0]);
      const water = Number(maxWaterRow.valor);
      const rain6h = round(rainHistory[area.idarea_risco].reduce((acc, x) => acc + x, 0), 2);
      const forecast = previsao_meteorologica.findLast((p) => p.idarea_risco === area.idarea_risco && p.data_emissao === observedText);
      const cls = classifyAlert(water, rain6h, Number(forecast.precipitacao_prevista_mm));

      if (cls.idnivel_alerta === 1 && rng() > 0.08) continue;

      const areaInfra = infraestrutura_urbana.filter((i) => i.idarea_risco === area.idarea_risco);
      const infraAlert = areaInfra.reduce((best, row) => previousWater[row.idinfraestrutura_urbana] > previousWater[best.idinfraestrutura_urbana] ? row : best, areaInfra[0]);

      const descricao = `Alerta ${cls.cor} na área ${area.nome}. `
        + `Nível máximo de água: ${water.toFixed(2)}%. `
        + `Precipitação acumulada 6h: ${rain6h.toFixed(2)} mm. `
        + `Precipitação prevista 1h: ${Number(forecast.precipitacao_prevista_mm).toFixed(2)} mm.`;

      alerta.push({
        idalerta,
        idnivel_alerta: cls.idnivel_alerta,
        idarea_risco: area.idarea_risco,
        idinfraestrutura_urbana: infraAlert.idinfraestrutura_urbana,
        data_alerta: observedText,
        descricao,
        score_risco: cls.score_risco,
        estado: cls.idnivel_alerta >= 3 ? 'ativo' : 'registado',
      });

      alerta_evidencia.push({
        idalerta_evidencia: idalerta_evidencia++,
        idalerta,
        idleitura_sensor: maxWaterRow.idleitura_sensor,
        idprevisao: null,
        tipo_variavel: 'nivel_agua_percentagem',
        valor_usado: water,
        unidade: '%',
        limiar_aplicado: '70/85/90%',
        contribuicao_para_alerta: 'Leitura máxima de nível de água na área.',
      });

      alerta_evidencia.push({
        idalerta_evidencia: idalerta_evidencia++,
        idalerta,
        idleitura_sensor: null,
        idprevisao: null,
        tipo_variavel: 'precipitacao_acumulada_6h',
        valor_usado: rain6h,
        unidade: 'mm',
        limiar_aplicado: '30/41/60 mm',
        contribuicao_para_alerta: 'Precipitação acumulada calculada sobre as últimas 6 horas.',
      });

      alerta_evidencia.push({
        idalerta_evidencia: idalerta_evidencia++,
        idalerta,
        idleitura_sensor: null,
        idprevisao: forecast.idprevisao,
        tipo_variavel: 'precipitacao_prevista_1h',
        valor_usado: Number(forecast.precipitacao_prevista_mm),
        unidade: 'mm',
        limiar_aplicado: '10/21/40 mm',
        contribuicao_para_alerta: 'Previsão meteorológica simulada para a próxima hora.',
      });

      for (const dest of recipientsForLevel(cls.idnivel_alerta, destinatario)) {
        alerta_destinatario.push({ idalerta, iddestinatario: dest.iddestinatario });

        const sendTime = addMinutes(observed, randint(rng, 1, 10));
        const estado = weightedChoice(rng, [['enviada', 0.60], ['confirmada', 0.35], ['falhada', 0.05]]);

        notificacao.push({
          idnotificacao: idnotificacao++,
          idalerta,
          iddestinatario: dest.iddestinatario,
          canal: cls.idnivel_alerta >= 3 ? 'email_sms' : 'email',
          data_envio: mysqlDate(sendTime),
          estado_envio: estado,
          data_confirmacao: estado === 'confirmada' ? mysqlDate(addMinutes(sendTime, randint(rng, 2, 30))) : null,
          mensagem: `${descricao} Medidas recomendadas associadas ao nível ${cls.cor}.`,
          erro_envio: estado === 'falhada' ? 'Erro simulado no envio.' : null,
        });
      }

      for (const plan of plano_alerta.filter((p) => p.idnivel_alerta === cls.idnivel_alerta)) {
        const started = rng() < (cls.idnivel_alerta >= 3 ? 0.85 : 0.50);
        const estado = started ? weightedChoice(rng, [['em_execucao', 0.5], ['concluido', 0.5]]) : 'pendente';
        const startAction = started ? addMinutes(observed, randint(rng, 5, 30)) : null;

        alerta_plano_acao.push({
          idalerta,
          idplano_acao: plan.idplano_acao,
          estado,
          responsavel: 'Operador Municipal',
          data_inicio: startAction ? mysqlDate(startAction) : null,
          data_conclusao: estado === 'concluido' ? mysqlDate(addMinutes(startAction, randint(rng, 30, 180))) : null,
          observacoes: started ? null : 'Ação ainda não iniciada.',
        });
      }

      relatorio.push({
        idrelatorio: idrelatorio++,
        data: mysqlDate(addMinutes(observed, 15)),
        descricao: `Relatório automático do alerta ${cls.cor}. Razões principais: ${cls.razoes.join(' ')} Score de risco: ${cls.score_risco.toFixed(2)}.`,
        idutilizador: utilizador[randint(rng, 0, utilizador.length - 1)].idutilizador,
        idalerta,
      });

      idalerta += 1;
    }
  }

  return {
    area_risco,
    infraestrutura_urbana,
    sensor,
    leitura_sensor,
    previsao_meteorologica,
    nivel_alerta,
    criterio_alerta,
    alerta,
    alerta_evidencia,
    utilizador,
    destinatario,
    alerta_destinatario,
    notificacao,
    plano_acao,
    plano_alerta,
    alerta_plano_acao,
    relatorio,
  };
}

/**
 * Parse CLI arguments.
 * @returns {{days: number, seed: number, output: string, sql: boolean, start: Date}}
 */
function parseArgs() {
  const cfg = {
    days: 14,
    seed: 42,
    output: 'synthetic_data',
    sql: false,
    start: null,
  };

  for (let i = 2; i < process.argv.length; i += 1) {
    const arg = process.argv[i];

    if (arg === '--days') cfg.days = Number.parseInt(process.argv[++i], 10);
    else if (arg === '--seed') cfg.seed = Number.parseInt(process.argv[++i], 10);
    else if (arg === '--output') cfg.output = process.argv[++i];
    else if (arg === '--sql') cfg.sql = true;
    else if (arg === '--start') cfg.start = new Date(process.argv[++i]);
    else if (arg === '--help' || arg === '-h') {
      console.log(`Usage:
  node generate_monitoring_data_node_v2.js --days 14 --output synthetic_data
  node generate_monitoring_data_node_v2.js --days 30 --seed 123 --output synthetic_data --sql
  node generate_monitoring_data_node_v2.js --days 30 --start 2026-01-01T00:00:00Z --output synthetic_data --sql`);
      process.exit(0);
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }

  if (!cfg.start) {
    const now = new Date();
    cfg.start = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  }

  if (!Number.isInteger(cfg.days) || cfg.days <= 0) throw new Error('--days must be a positive integer.');
  if (!Number.isInteger(cfg.seed)) throw new Error('--seed must be an integer.');
  if (Number.isNaN(cfg.start.getTime())) throw new Error('--start must be a valid date.');

  return cfg;
}

/** Main entry point. */
function main() {
  const cfg = parseArgs();
  const tables = generateData(cfg);

  fs.mkdirSync(cfg.output, { recursive: true });

  for (const [tableName, rows] of Object.entries(tables)) {
    writeCsv(path.join(cfg.output, `${tableName}.csv`), rows);
  }

  if (cfg.sql) {
    writeSql(path.join(cfg.output, 'insert_synthetic_data.sql'), tables);
  }

  console.log('Synthetic data generated successfully.');
  console.log(`Output directory: ${path.resolve(cfg.output)}`);
  for (const [tableName, rows] of Object.entries(tables)) {
    console.log(`- ${tableName}: ${rows.length} rows`);
  }
}

if (require.main === module) {
  try {
    main();
  } catch (error) {
    console.error(`Error: ${error.message}`);
    process.exit(1);
  }
}

module.exports = { classifyAlert, generateData };
